syntax = "proto3";

package debug;

// 怪物预算信息
message EnemyBudgetData {
  string enemy_type = 1;
  uint64 budget = 2;
}

// 用来debug的关卡信息
message LevelDebugData {
  repeated EnemyBudgetData enemy_budget_data = 1;
  int32 server_tick = 2;
  int32 cur_stage_id = 3;
  uint64 spwan_time_count_down_ms = 4;
  uint64 stage_time_seconds = 5;
  int32 enemy_count = 6;
  int32 normal_enemy_count = 7;
}


message ServerMessage {
    string run_id = 1;
    uint64 server_tick = 2;

    oneof payload {
        LevelDebugData level_debug_data = 3;
    }
}